### ISSUE TITLE
Data set configuration error

### ISSUE THREAD

**Issue by PerrineL** [Gladior-B-V/majestic-connector#3]
Hi there,

I'm trying to use gladior to show our Majestic's data in Looker but I keep getting a data set configuration error. 

The connection in Looker seems to have worked well as I can see all Majestic's fields available in my Looker project but when I pull any metrics into the page, I get a data set configuration error / Community Connector error. See error below:

<img width="442" alt="gladior - looker error " src="https://github.com/Gladior-B-V/majestic-connector/assets/150888424/3b3ab4b1-bfcd-4b0f-9daf-3a328adac003">

I checked the troubleshooting guide on your website and Majestic's website but I couldn't fix my issue unfortunately. I know it is a very broad question but would you have any extra troubleshooting steps I could use? 

Thanks,
Perrine

**Comment by zoedufrenne** [comment]
Hi @PerrineL , When I saw your message come in I went to check right away. But I get no error myself. see also example. https://lookerstudio.google.com/reporting/bd853f4d-d4cb-49b5-9a9c-b09bd76d827e 

It doesn't seem to be because of the connector. Is the api token from Majestic still working? Or maybe you don't have the right permissions to create this?

**Comment by PerrineL** [comment]
Hi Zoe,

Thanks a lot for your prompt reply. I realised it worked well when I connected with the 'Data Hub' connector, not the 'Majestic' one. 

![gladior connector looker](https://github.com/Gladior-B-V/majestic-connector/assets/150888424/8608c5ee-13b7-43e8-9824-eb2b584ef149)

All good now! Can I also ask a few questions please:
- Do I need to have data hub connected to my google account as a 3rd party app to make it work?
- I understand this service is free at the moment, is there a cap or a plan to charge customers in the future?
- Is there a way to extract the 'follow' dimension (ie to know if the link is DoFollow or NoFollow?)
- also I would like to see how many referring domains we got over time but I seem unable to use the 'refdomains' with the date dimension, is that normal?

Thanks a lot!
Perrine

**Comment by PerrineL** [comment]
Hi Zoe, 
Hope you're well. One more question please, the date range control doesn't seem to work for me, i.e the numbers either don't change or the data don't appear at all (I get the data set configuration error). I am using the fresh index.
Do you have this issue too or is it because the date range control only works with the historic index?

**Comment by zoedufrenne** [comment]
Hi @PerrineL ,

Thanks for letting us know. I will let development know!

**- Do I need to have data hub connected to my google account as a 3rd party app to make it work?** 
You can just login with your account in the Data Hub to make the Data Hub work. But when you want the data in your looker studio dashboard, you need to connect Data Hub with Google as a 3rd party app. 

**- I understand this service is free at the moment, is there a cap or a plan to charge customers in the future?**
The Data Hub will stay for free, the way it is now. We are developing new things and these will be for a paid subcription. Such as connect you own templates & extra possibilties with connector to connect multiple accounts at once. 

**- Is there a way to extract the 'follow' dimension (ie to know if the link is DoFollow or NoFollow?)**
Follow for Majestic? I don't understand what metric this is. Can you explain.

**- also I would like to see how many referring domains we got over time but I seem unable to use the 'refdomains' with the date dimension, is that normal?**
Yes this is normal, to see the referring domains over time, we need to set up a database where we 'save' the old data. This cost a lot of data. That's why we don't offer this option. 

Majestic data doesn't work with the data, because the data is 'saved' it's 'real time'. (data updates every 24 hours).

**Comment by PerrineL** [comment]
Hi Zoe,

Thanks for your reply and explanation.

Regarding point 3 and the 'follow' dimension, we would like to filter the links that are DoFollow only (as opposed to NoFollow). There's a NoFollow filter in Majestic but I can't see this dimension in Looker. There's 'Link Type' in Looker but it shows image vs text link so not what I am looking for. Do you know if the 'NoFollow' filter has been/will be imported?

As for point 4, I am not sure I understand sorry. We can see the backlinks/referring domains from the past years in majestic, and the historical backlinks are getting pulled in Looker, so I would imagine the referring domains would follow the same process?

Thanks a lot,


Perrine Mignot Leung

Data Analyst

Jaywing Australia

________________________________

**Comment by zoedufrenne** [comment]
Hi @PerrineL , updates on the Majestic connector is not in our planning. We will continue to support the connector and if it's not working we will fix it. But we won't add new data fields to the connector. These fields are all available in the connector: https://datahub.gladior.com/data-sources/support-majestic-connector/ 

What you'll see in Looker Studio is all we get from the majestic API. We don't change the the data from Majestic. 
Did you try to change the date selector to a longer period of time to see if you'll see more refDomains?

**Comment by PerrineL** [comment]
Hi Zoe,

No problem and thanks for the update!

Have a good Christmas holiday.


Perrine Mignot Leung

Data Analyst
Jaywing Australia
Working Wednesday, Thursday, Friday



________________________________
